name: DRAVE Validation

on:
  push:
    paths:
      - 'detections/**'
      - '.github/workflows/drave-validation.yml'
  pull_request:
    paths:
      - 'detections/**'
  workflow_dispatch:
    inputs:
      bootstrap:
        description: 'Run in bootstrap mode'
        required: false
        default: 'false'

jobs:
  validate-detection:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run DRAVE Detection Validation
        id: drave_validation
        continue-on-error: true
        uses: Rushi19-04/DRAVE/action/drave-action-repo@main
        with:
          api-url: https://drave-bfsi.onrender.com
          rule-paths: detections
          api-key: ${{ secrets.DRAVE_API_KEY }}
          bootstrap: ${{ github.event.inputs.bootstrap || 'true' }}

